[package]
name = "screenshot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
home = "0.5.4"
chrono = "0.4.23"
winapi = "0.3.9"
image = "0.24.5"